#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydb
#    username: manish
#    password: Manish@7200
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update

server:
  port: 8081
